---
language: go
dist: xenial
git:
  depth: 1
notifications:
  email: false
script:
  - go run server/server.go


matrix:
  include:
  -
    addons:
      chrome: stable
    before_install: cd frontend
    language: node_js
    node_js:
      - "10"
